# Generated by Django 4.2.6 on 2023-12-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remuneration_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default='Default Department', max_length=100),
        ),
    ]
